### ISSUE TITLE
iPad SafariとMac Safariで画像が読み込まれない。

### ISSUE THREAD

**Issue by regepan** [Takazudo/jQuery.ImgLoader#1]
## 下記環境で
- iPad OS 5.1.1 + Safari
- Mac OSX 10.4 Safari4.1.3
- Windows7 Safari 5.1.7
## 下記デモの処理が途中で止まります。

http://takazudo.github.com/jQuery.ImgLoader/demo2/example.html
## 現状わかっていること。
- iPhone 3GS OS6.0 + Safariでは最後まで実行され、画像は表示される。 
- 読み込む画像の枚数を1枚にしても同じような止まり方をし、画像も表示されない。
- 上記iPad SafariとMac Safariでは止まり方が似ている。（1度目のGETリクエストしか実行されない。）
## 関係あるかどうかわからないけど

iPadではここが動いていない。
https://github.com/Takazudo/jQuery.ImgLoader/blob/gh-pages/jquery.imgloader.js#L69
## その他

`$.Deferred()` のデバッグの仕方がわからないので、時間ができ次第デバッグの続きはやるかもしれません。

**Comment by Takazudo** [comment]
あとで見てみます。ありがとうございます！

**Comment by Takazudo** [comment]
iOS5.1 iPadで試してみたところ、再現されました。
本件、XHR2の対応がそのへんのボーダーのブラウザーで不十分である可能性が高いです。
ひとまず使いたい場合、useXHR2: false にしてお使いください。
それだと動作しました。
あとで突っ込んで見てみます。
ありがとうございます！

**Comment by regepan** [comment]
```
useXHR2: false
```

で、上記safari全てで動きました！
ありがとうございます！
jQuery.Deferred() 難しいっすね！

**Comment by Takazudo** [comment]
なんかそのご指摘の部分は、cachedFunctionとかいうJavaScriptのテクい技らしくて、僕もよーーーく見ないとどうなってるのか思い出せませんｗ ありがとございます！
